
# In The Name Of God
# ========================================
# [] File Name : pipe.c
#
# [] Creation Date : 16-10-2015
#
# [] Last Modified : Fri 16 Oct 2015 5:08:00 PM IRST
#
# [] Created By : Sajjad Rahnama (sajjad.rahnama7@gmail.com)
# =======================================


CCFLAGS = -std=c99



pipe : pipe.c prime_func.c
	gcc prime_func.c pipe.c -o pipe $(CCFLAGS)
